# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: macos-13

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm i
  displayName: 'npm i'
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '8'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: Gradle@3
  inputs:
    gradleWrapperFile: './android/gradlew'
    workingDirectory: '$(Build.SourcesDirectory)/android'
    options: '--stacktrace'
    tasks: 'bundleRelease --warning-mode all'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
- task: CopyFiles@2
  inputs:
    Contents: |
      **/*.apk
      **/*.aab
    TargetFolder: '$(Build.ArtifactStagingDirectory)/android'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'